# Generated by Django 5.2 on 2026-02-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_deliverypincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypincode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
